FROM --platform=linux/amd64 ubuntu:20.04 as builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential libjpeg-dev

ADD . /repo
WORKDIR /repo
RUN ./configure
RUN make -j8

RUN mkdir -p /deps
RUN ldd /repo/jpeginfo | tr -s '[:blank:]' '\n' | grep '^/' | xargs -I % sh -c 'cp % /deps;'

FROM ubuntu:20.04 as package

COPY --from=builder /deps /deps
COPY --from=builder /repo/jpeginfo /repo/jpeginfo
ENV LD_LIBRARY_PATH=/deps
